#!/bin/bash -e
##
## summary of how this script can be called:
##        * <new-preinst> install
##        * <new-preinst> install <old-version>
##        * <new-preinst> upgrade <old-version>
##        * <old-preinst> abort-upgrade <new-version>
##

. /usr/share/debconf/confmodule

# creating candid group if he isn't already there
if ! getent group candid >/dev/null; then
    # Adding system group: candid.
    addgroup --system candid >/dev/null
fi

# creating candid user if he isn't already there
if ! getent passwd candid >/dev/null; then
    # Adding system user: candid.
    adduser \
      --system \
          --disabled-login \
      --ingroup candid \
      --gecos "identity server" \
      --shell /bin/false \
      candid  >/dev/null
fi

# create log dir
mkdir -p /var/log/identity
chown candid:candid /var/log/identity
